version: '3.7'

services:

  project-manager:
    container_name: project-manager
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/project-manager'
      - '/project-manager/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - json-server
    command: npm start

  json-server:
    container_name: json-server
    volumes:
      - '.:/project-manager'
      - '/project-manager/node_modules'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    command: npm run json-server
    tty: true